# developement file

services:
  backend:
    build: ./language_app/
    container_name: language-app-backend
    env_file:
      - ./language_app/.env
    
  nginx:
    build: 
      context: . 
      dockerfile: ./nginx/Dockerfile
    container_name: language-app-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./react-app/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:80 || exit 1"]
      interval: 1m30s
      timeout: 20s
      retries: 5
      start_period: 30s
