

services:
  backend:
    build: ./language_app/
    container_name: language-app-backend
    ports:
      - "8000:8000"
    env_file:
      - ./language_app/.env
    
  nginx:
    build: 
      context: . 
      dockerfile: ./nginx/Dockerfile
    container_name: language-app-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./react-app/.env