

all_genres = ['Slice of Life', 'Adventure', 'Silly', 'Mystery', 'Food', 'Travel', 'Animals']

general_themes = [
'Friendship', 'Discovery', 'Challenge', 'Everyday life', 'Problem solving',
'Nature', 'Food adventure', 'Travel mishap', 'Unexpected event', 'Learning something new',
'Helping others', 'A funny misunderstanding', 'A small town secret', 'Magical encounter',
'Time travel (simple)', 'Robot friend', 'Talking animal', 'Delicious food', 'Beautiful scenery',
'Kindness', 'Bravery', 'Curiosity', 'Sharing', 'Patience', 'Gratitude', 'Teamwork',
'Honesty', 'Responsibility', 'Creativity', 'Excitement', 'Relaxation', 'Celebration',
'Surprise', 'Growth', 'Helpfulness', 'Politeness', 'Fun', 'Comfort', 'Home', 'Memories',
'Tradition', 'Local Culture', 'Seasons (General Sense)', 'Weather (General Sense)',
'Travel (General Sense)', 'Food (General Sense)', 'Music (General Sense)', 'Art (General Sense)',
'Games (General Sense)', 'Learning', 'Making Mistakes (and Learning from them)',
'Overcoming Obstacles', 'Simple Pleasures',

# --- Specific Themes ---
'Making a New Friend', 'Exploring a New Shop', 'Going to a Festival Game', 'Trying a New Japanese Snack', 'Visiting a Local Park Festival (Simplified)',
'Seeing Street Performers (Simple)', 'Helping an Elderly Person (Simple Act)', 'Getting Lost and Finding the Way Back (Simplified)', 'Sharing Lunch with Classmates',
'Exchanging Small Gifts with Friends', "Autumn Leaves in Japan", "Cherry Blossoms", "Summer Fireworks", "Winter Illuminations in Japan",

# --- More Emotional Range ---
'Quiet Reflection', 'Peaceful Moment', 'Gentle Rain', 'Silly Mistake', 'Funny Surprise', 'Unexpected Laughter', 'Small Mystery', 'Hidden Message', 'Unexplained Event',

# --- More Action/Activity Focused Themes ---
'Building Something Together', 'Organizing an Event', 'Participating in a Contest', 'Preparing for a Trip', 'Having a Practice Session', 'Trying a New Recipe', 'Making Music',

# --- More "Learning" Focused Themes ---
'Learning a New Japanese Word', 'Practicing Japanese Greetings', 'Trying to Read Japanese', 'Asking for Help in Japanese', 'Understanding Japanese Customs', 
'Learning about Japanese Culture', 'Studying for a Test (simple)',

# --- More "Cultural Exploration" Themes ---
'Visiting a Japanese Garden', 'Trying Japanese Calligraphy (Shodo)', 'Learning about Japanese Tea', 'Exploring a Japanese Neighborhood', 
'Visiting a Local Japanese Market', 'Trying on a Kimono/Yukata', 'Seeing a Sumo Match (simplified)',

# --- More "Problem-Solving" or "Mini-Challenge" Themes ---
'Finding a Way Home', 'Fixing Something Broken', 'Making a Decision', 'Waiting Patiently', 'Helping a Lost Pet', 'Cleaning up a Mess', 'Sharing a Toy',
]


story_settings_locations = [
    # --- Home/Indoor Settings ---
    "in a cozy living room",
    "in a quiet bedroom",
    "in a bright kitchen",
    "in a small dining room",
    "in a sunny garden",
    "on a balcony overlooking the city",
    "in a hallway of a house",
    "in a home office",
    "in a child's playroom",
    "in a garage filled with tools",
    "in a traditional Japanese tatami room (washitsu)",
    "in a modern apartment living room",
    "in a cluttered attic",
    "in a spacious veranda",
    "in a basement that is a bit dark",
    "in a comfortable study room",
    "inside a walk-in closet",
    "in a brightly lit sunroom",
    "in a pantry filled with food",
    "in a laundry room with the washing machine running",
    "at a friends house"

    # --- School/Work Settings ---
    "in a classroom at school",
    "in the school hallway",
    "in the school library",
    "in the school cafeteria",
    "on the school playground",
    "in a teacher's office",
    "in an art room filled with paintings",
    "in a music room with instruments",
    "in a science lab with beakers and tubes",
    "in a gymnasium during basketball practice",
    "in a quiet corner of the library",
    "in a busy office cubicle",
    "in a conference room during a meeting",
    "in a break room at work",
    "in a reception area of an office",
    "in a design studio with computers",
    "in a workshop with tools and wood",
    "in a small office overlooking a street",
    "in a large, open-plan office",
    "in a recording studio with microphones",

    # --- Outdoor/Nature Settings ---
    "in a park filled with trees",
    "in a flower garden",
    "by a small pond",
    "on a forest path",
    "on a sandy beach",
    "by the ocean waves",
    "on a grassy hill",
    "under a large cherry blossom tree (sakura)",
    "in a bamboo grove",
    "near a flowing river",
    "in a quiet corner of a large park",
    "on a playground with swings and slides",
    "in a vegetable garden",
    "in a field of tall grass",
    "on a mountain trail",
    "by a waterfall",
    "in a clearing in the woods",
    "on a rocky coastline",
    "in a field of sunflowers",
    "under a starry night sky",

    # --- Commercial/Town Settings ---
    "in a bustling supermarket",
    "in a quiet bookstore",
    "in a small local cafe",
    "in a busy train station",
    "on a crowded shopping street",
    "in a quiet residential street",
    "in a traditional Japanese sweets shop (wagashiya)",
    "in a ramen shop",
    "in a sushi restaurant",
    "in a bakery with the smell of fresh bread",
    "in a clothing store with colorful clothes",
    "in a toy store filled with games",
    "in a small neighborhood park",
    "at a bus stop waiting for the bus",
    "in a movie theater lobby",
    "at an ice cream shop",
    "in a flower shop filled with bouquets",
    "in a stationery store with pens and paper",
    "at a fruit and vegetable stand",
    "in a busy town square",

    # --- Japanese Specific Settings (Cultural/Unique) ---
    "at a Shinto shrine (jinja)",
    "at a Buddhist temple (tera/o-tera)",
    "at a summer festival (matsuri) with food stalls",
    "at a fireworks festival (hanabi taikai)",
    "in a traditional Japanese garden (nihon teien)",
    "in a hot spring bath (onsen)",
    "in a public bathhouse (sento)",
    "on a bullet train (shinkansen)",
    "at a traditional tea ceremony (chanoyu/sado)",
    "in a karaoke box",
    "at a fish market",
    "in an anime/manga store",
    "at a cherry blossom viewing party (hanami)",
    "at a Tanabata festival with decorations",
    "at a Bon Odori dance festival",
    "at a local shopping arcade (shotengai)",
    "in a pachinko parlor (noisy and bright)",
    "at a vending machine corner",
    "in a capsule hotel",
    "at a countryside rice field",
]


starting_situations = [
    # --- Sensory Start (Focus on perception) ---
    "The character wakes up to a strange sound.",
    "The character smells something delicious.",
    "The character sees something sparkling in the distance.",
    "The character feels a gentle breeze.",
    "The character hears someone calling their name.",
    "The character notices a sudden silence.",
    "The character sees a shadow moving quickly.",
    "The character hears music coming from somewhere nearby.",
    "The character smells rain in the air.",
    "The character feels something soft brush against their leg.",
    "The character tastes something unexpectedly sweet/sour.",
    "The character sees a bright light flash suddenly.",
    "The character hears a faint whisper.",
    "The character feels the ground tremble slightly.",
    "The character smells smoke, but there's no fire nearby.",
    "The character sees something colorful fluttering in the wind.",
    "The character hears a bird singing a very unusual song.",
    "The character feels a drop of water on their head, but it's not raining.",
    "The character tastes salt on their lips, even though they haven't eaten anything salty.",
    "The character sees something glowing faintly in the dark.",
    "The character wakes up feeling unusually cold.",
    "The character smells freshly cut grass.",
    "The character sees something reflecting sunlight brightly.",
    "The character feels a vibration in their pocket.",
    "The character hears someone humming a familiar tune.",
    "The character notices a change in the air pressure.",
    "The character hears the gentle lapping of water.",
    "The character tastes a metallic tang in their mouth (subtly unusual).",
    "The character hears a rhythmic tapping sound.",
    "The character feels a slight tingling sensation in their fingertips.",
    "The character smells something faintly floral, even indoors.",
    "The character sees an object slightly out of focus, as if their vision blurred momentarily.",
    "The character hears the rustling of leaves, even though there's no wind.",
    "The character feels a sudden warmth on their face.",
    "The character tastes a hint of spice, even though they are not eating anything.",
    "The character sees a pattern of light and shadow that seems to shift and change.",


    # --- Discovery Start (Finding something unexpected) ---
    "The character finds a small, colorful stone on the path.",
    "The character discovers a hidden door in their house.",
    "The character finds a lost toy in the park.",
    "The character discovers a small, handwritten note.",
    "The character finds a map that looks old.",
    "The character unearths something buried in the garden.",
    "The character finds a key that doesn't seem to belong to anything they know.",
    "The character discovers a beautiful flower they've never seen before.",
    "The character finds a small box with something inside.",
    "The character discovers footprints in the snow/sand.",
    "The character finds a single glove/sock lying on the ground.",
    "The character discovers a small, abandoned bird's nest.",
    "The character finds a coin that looks very old and shiny.",
    "The character discovers a drawing hidden inside a book.",
    "The character finds a set of colorful marbles scattered on the floor.",
    "The character discovers a small, locked diary.",
    "The character finds a feather that is an unusual color.",
    "The character discovers a strange symbol carved into a tree.",
    "The character finds a photograph that they don't recognize.",
    "The character discovers a set of small, animal figurines arranged neatly.",
    "The character finds a small, intricately carved wooden box.",
    "The character discovers a faded photograph tucked inside a wallet.",
    "The character finds a torn piece of fabric with an unusual pattern.",
    "The character discovers a set of dominoes arranged in a line.",
    "The character finds a small, smooth stone with a hole through it.",
    "The character discovers a dried leaf pressed between the pages of a book.",
    "The character finds a ticket stub for an event they don't remember attending.",
    "The character discovers a small, porcelain doll missing an eye.",
    "The character finds a set of colorful buttons scattered on a table.",
    "The character discovers a small, origami figure tucked under a cushion.",
    "The character finds a postcard with a picture of a place they've never been.",
    "The character discovers a small, leather-bound notebook filled with sketches.",
    "The character finds a rubber band stretched into an unusual shape.",
    "The character discovers a single playing card face down.",
    "The character finds a small, empty birdcage.",
    "The character discovers a set of dice with unusual symbols instead of numbers.",
    "The character finds a key attached to a brightly colored ribbon.",
    "The character discovers a small, glass bottle filled with colored sand.",
    "The character finds a fortune cookie with a blank fortune inside.",
    "The character discovers a small, wind-up toy that doesn't seem to work.",


    # --- Encounter Start (Meeting someone or something new) ---
    "The character meets a friendly dog in the park.",
    "The character encounters a new student at school.",
    "The character meets an elderly person who needs help.",
    "The character encounters a street performer.",
    "The character sees someone struggling to carry something.",
    "The character meets a lost child.",
    "The character encounters a talking animal (in a fantasy context, subtly implied).",
    "The character sees a group of people gathered around something.",
    "The character meets a new neighbor.",
    "The character encounters someone selling interesting food.",
    "The character sees someone waving to them from across the street, but they don't recognize them.",
    "The character encounters a cat that seems to be trying to lead them somewhere.",
    "The character meets a delivery person with a package for them, but they weren't expecting anything.",
    "The character sees someone wearing a very unusual hat.",
    "The character encounters a group of children playing a game they don't know.",
    "The character meets someone who is looking for directions.",
    "The character sees someone painting a picture in the park.",
    "The character encounters a musician playing a beautiful instrument.",
    "The character meets someone who seems to have dropped something important.",
    "The character sees someone looking lost and confused.",
    "The character meets someone wearing mismatched shoes and socks.",
    "The character encounters a group of tourists taking photos of everything.",
    "The character sees someone carrying a musical instrument case.",
    "The character meets a street artist drawing portraits.",
    "The character sees someone handing out flyers for a local event.",
    "The character encounters a mime performing silently.",
    "The character meets someone with a very unusual hairstyle.",
    "The character sees someone riding a unicycle.",
    "The character meets someone who is trying to sell handmade jewelry.",
    "The character sees someone walking a very small dog in a stroller.",
    "The character encounters a group of people playing a board game outdoors.",
    "The character meets someone who offers them a flower.",
    "The character sees someone practicing magic tricks with cards.",
    "The character encounters a person dressed in a slightly old-fashioned style.",
    "The character meets someone who is carrying a brightly colored umbrella on a sunny day.",
    "The character sees someone looking intently at a map spread out on the ground.",
    "The character encounters a group of people having a picnic.",
    "The character meets someone who is trying to learn Japanese from a phrasebook.",
    "The character sees someone wearing a pair of very large headphones.",


    # --- Action Start (Character is already doing something) ---
    "The character is walking home from school/work.",
    "The character is playing in the park.",
    "The character is eating lunch at school/work.",
    "The character is reading a book in their room.",
    "The character is helping with chores at home.",
    "The character is riding a bike in the park.",
    "The character is drawing/painting a picture.",
    "The character is watering plants in the garden.",
    "The character is cooking a simple meal.",
    "The character is waiting for someone at a meeting place.",
    "The character is getting ready to go out.",
    "The character is cleaning their room.",
    "The character is practicing a musical instrument.",
    "The character is writing in a notebook.",
    "The character is looking out the window.",
    "The character is choosing what to wear for the day.",
    "The character is packing a bag.",
    "The character is setting the table for a meal.",
    "The character is organizing their desk/workspace.",
    "The character is looking at photos in an album.",
    "The character is writing a haiku poem.",
    "The character is practicing origami.",
    "The character is arranging flowers in a vase.",
    "The character is trying to solve a crossword puzzle.",
    "The character is listening to a Japanese language learning podcast.",
    "The character is checking the weather forecast on their phone.",
    "The character is making a to-do list for the day.",
    "The character is choosing what to have for breakfast.",
    "The character is watering their bonsai tree.",
    "The character is sketching in a small sketchbook.",
    "The character is practicing calligraphy with a brush and ink.",
    "The character is setting up a simple tea ceremony.",
    "The character is sorting through their collection of postcards.",
    "The character is looking at a Japanese phrasebook.",
    "The character is planning a day trip to a nearby town.",
    "The character is trying to assemble a small model kit.",
    "The character is practicing their Japanese pronunciation in a mirror.",
    "The character is wrapping a small gift neatly.",
    "The character is preparing a simple Japanese snack.",


    # --- Question/Unusual Circumstance Start (Prompting curiosity) ---
    "The character notices that something is missing from their usual place.",
    "The character receives a mysterious message.",
    "The character realizes they have forgotten something important.",
    "The character sees something unusual happening outside their window.",
    "The character finds that their favorite thing is not working.",
    "The character wakes up and the weather is very different from yesterday.",
    "The character notices that time seems to be going by very quickly/slowly.",
    "The character finds that something in their house has moved to a different place.",
    "The character realizes they are in a place they don't recognize (subtly, within a familiar setting).",
    "The character hears a rumor about something interesting happening nearby.",
    "The character finds a door unlocked that they usually keep locked.",
    "The character sees a light turned on in a room that should be empty.",
    "The character realizes they have an extra item in their bag that they didn't put there.",
    "The character finds that their pet is behaving strangely.",
    "The character notices that a familiar sound is suddenly absent.",
    "The character receives a phone call from an unknown number.",
    "The character finds that their reflection in a mirror seems slightly different.",
    "The character realizes they are wearing mismatched socks/shoes.",
    "The character finds that their favorite snack is unexpectedly gone.",
    "The character notices that a clock in their house is showing the wrong time.",
    "The character notices that their reflection is wearing something different.",
    "The character receives a letter written in elegant calligraphy, but they don't recognize the address.",
    "The character finds that a book they were reading has changed its cover.",
    "The character sees their pet reacting to something invisible.",
    "The character realizes they are humming a song in a language they don't know.",
    "The character finds a message written in code on a napkin.",
    "The character notices that their shadow is moving at a different pace than they are.",
    "The character receives an email with no subject line and a strange attachment.",
    "The character finds that a piece of furniture in their room has changed color.",
    "The character realizes they are holding an object they don't remember picking up.",
    "The character finds a set of footprints leading away from their house, but it hasn't rained.",
    "The character sees a street sign that seems to have changed its name.",
    "The character realizes they have an extra key on their keychain that they don't recognize.",
    "The character finds that their pet is staring intently at a blank wall.",
    "The character notices that a familiar smell has suddenly disappeared.",
    "The character receives a voicemail message that is just static.",
    "The character finds that their watch/clock is running backwards.",
    "The character realizes they are carrying an extra umbrella, even though they only own one.",
    "The character finds that their favorite mug is in a place it shouldn't be.",
    "The character notices that a plant in their house has suddenly started blooming out of season.",
]


all_japanese_names = [
    "Aiba", "Aika", "Aki", "Akihito", "Akihiro", "Akira", "Akari", "Akatsuki", "Akane", "Amato",
    "Amane", "Ami", "An", "Ao", "Aoi", "Arashi", "Arata", "Asahi", "Asuka", "Atsuki", "Ayumu",
    "Beniko", "Botan", "Chiaki", "Chiharu", "Chikao", "Chinatsu", "Chihiro", "Chou", "Daigo",
    "Daichi", "Daijiro", "Daiki", "Den", "Eiji", "Eito", "Ena", "Erika", "Fuji", "Fuuta", "Gaku",
    "Gin", "Ginga", "Goro", "Haku", "Hajime", "Haru", "Haruna", "Hayao", "Hayate",
    "Hazuki", "Hibiki", "Hideki", "Hideo", "Hikaru", "Hina", "Hinata", "Hiroki", "Hiroshi", "Hiroto",
    "Hiyo", "Homare", "Honami", "Honoka", "Hoshi", "Hotaka", "Hotaru", "Ibuki", "Ikkaku", "Inori",
    "Issei", "Itsuki", "Izumi", "Jin", "Jiro", "Jo", "Jouji", "Jun", "Junna", "Junpei", "Kaede",
    "Kaguya", "Kai", "Kaito", "Kakeru", "Kana", "Kanae", "Kanako", "Kanon", "Kanata", "Kanna",
    "Kaori", "Karin", "Kasumi", "Katsumi", "Kaoru", "Kazane", "Kazuhiko", "Kazuki", "Kazuma", "Kazumi",
    "Keigo", "Keiko", "Keisuke", "Keita", "Keito", "Ken", "Kenichi", "Kenji", "Kenshin", "Kenta",
    "Kira", "Kiyoka", "Kiyomasa", "Kiyomi", "Kiyora", "Kiyoshi", "Kokoa", "Koharu", "Koki", "Komugi",
    "Konatsu", "Kota", "Kotone", "Kotomi", "Kou", "Kouhei", "Kouki", "Kouta", "Kouya", "Luna",
    "Madoka", "Maho", "Mai", "Makoto", "Mamoru", "Manabu", "Manami", "Mao", "Marina", "Marin",
    "Masaki", "Masaru", "Masato", "Masayoshi", "Mayu", "Mei", "Michio", "Miharu", "Miki", "Miku",
    "Mina", "Minami", "Minato", "Minori", "Mio", "Miori", "Mitsu", "Mitsuki", "Miyu", "Mizuki",
    "Mizuho", "Moe", "Momiji", "Momoka", "Mutsuki", "Nagi", "Nagisa", "Nao", "Naohiro", "Naoki",
    "Naoto", "Nanami", "Natsuki", "Natsume", "Nene", "Niko", "Noboru", "Nobukazu", "Nonoka", "Nozomi",
    "Oka", "Osamu", "Rai", "Raiden", "Raiga", "Raito", "Raizo", "Raku", "Ramu", "Ran", "Ranji",
    "Rei", "Reiji", "Reina", "Remi", "Ren", "Renka", "Renji", "Riku", "Rikuo", "Rin", "Rina",
    "Rinon", "Rintaro", "Riona", "Ririka", "Risa", "Ritsu", "Rumi", "Runo", "Ruri", "Ruriha",
    "Ryoga", "Ryohei", "Ryouma", "Ryota", "Ryosei", "Ryusei", "Saburo", "Sachiko", "Saku", "Sakura",
    "Sakuyo", "Sanosuke", "Sango", "Sara", "Saki", "Sakuyo", "Sanosuke", "Sango", "Sara", "Saki",
    "Satoshi", "Satsuki", "Sayaka", "Seiji", "Sen", "Senichi", "Serina", "Setsuka", "Setsuna", "Shin",
    "Shinji", "Shion", "Shiori", "Shizuka", "Shogo", "Sho", "Shota", "Shun", "Shunya", "Sohma",
    "Sora", "Sota", "Sou", "Souma", "Subaru", "Suisei", "Sumire", "Sumireko", "Susumu", "Suzuka",
    "Taichi", "Taiga", "Taiyo", "Takashi", "Takumi", "Taku", "Takeshi", "Takeru", "Taro", "Tatsuya",
    "Tetsuya", "Toki", "Toma", "Tomoe", "Tomoki", "Tomomi", "Tomoya", "Toru", "Tsubaki", "Tsubasa",
    "Tsukasa", "Tsukiyo", "Tsumugi", "Tsuyu", "Tsuyoshi", "Ukyo", "Umi", "Utae", "Wakaba", "Wakana",
    "Wataru", "Yamato", "Yasuhiro", "Yae", "Yo", "Yoichi", "Yoko", "Yori", "Yosei", "Yoshiaki",
    "Yoshihiro", "Yoshiko", "Yoshio", "Youko", "Yuichi", "Yuito", "Yuuka", "Yuuki", "Yuukihiro", "Yukihito",
    "Yukiho", "Yukio", "Yuna", "Yuumi", "Yuu", "Yuuka", "Yuumi", "Yuusei", "Yuzuki", "Yuzuha", "Yuzuyu",
    "Yurara", "Yurika", "Yuto", "Yuuya", "Zen", "Zenjiro", "Zin", "Zoe"
]