

all_genres = ['Slice of Life', 'Adventure', 'Silly', 'Comedy', 'Mystery', 'Food', 'Travel', 'Animals']

general_themes = [
'Friendship', 'Discovery', 'Challenge', 'Everyday life', 'Problem solving',
'Nature', 'Food adventure', 'Travel mishap', 'Unexpected event', 'Learning something new',
'Helping others', 'A funny misunderstanding', 'A small town secret', 'Magical encounter',
'Time travel (simple)', 'Robot friend', 'Talking animal', 'Delicious food', 'Beautiful scenery',
'Kindness', 'Bravery', 'Curiosity', 'Sharing', 'Patience', 'Gratitude', 'Teamwork',
'Honesty', 'Responsibility', 'Creativity', 'Excitement', 'Relaxation', 'Celebration',
'Surprise', 'Growth', 'Helpfulness', 'Politeness', 'Fun', 'Comfort', 'Home', 'Memories',
'Tradition', 'Local Culture', 'Seasons (General Sense)', 'Weather (General Sense)',
'Travel (General Sense)', 'Food (General Sense)', 'Music (General Sense)', 'Art (General Sense)',
'Games (General Sense)', 'Learning', 'Making Mistakes (and Learning from them)',
'Overcoming Obstacles', 'Simple Pleasures',

# --- Specific Themes ---
'Making a New Friend', 'Exploring a New Shop', 'Going to a Festival Game', 'Trying a New Japanese Snack', 'Visiting a Local Park Festival (Simplified)',
'Seeing Street Performers (Simple)', 'Helping an Elderly Person (Simple Act)', 'Getting Lost and Finding the Way Back (Simplified)', 'Sharing Lunch with Classmates',
'Exchanging Small Gifts with Friends', "Autumn Leaves in Japan", "Cherry Blossoms", "Summer Fireworks", "Winter Illuminations in Japan",
]

starting_situations = [
    # --- Sensory Start (Focus on perception) ---
    "The character wakes up to a strange sound.",
    "The character smells something delicious.",
    "The character sees something sparkling in the distance.",
    "The character feels a gentle breeze.",
    "The character hears someone calling their name.",
    "The character notices a sudden silence.",
    "The character sees a shadow moving quickly.",
    "The character hears music coming from somewhere nearby.",
    "The character smells rain in the air.",
    "The character feels something soft brush against their leg.",
    "The character tastes something unexpectedly sweet/sour.",
    "The character sees a bright light flash suddenly.",
    "The character hears a faint whisper.",
    "The character feels the ground tremble slightly.",
    "The character smells smoke, but there's no fire nearby.",
    "The character sees something colorful fluttering in the wind.",
    "The character hears a bird singing a very unusual song.",
    "The character feels a drop of water on their head, but it's not raining.",
    "The character tastes salt on their lips, even though they haven't eaten anything salty.",
    "The character sees something glowing faintly in the dark.",

    # --- Discovery Start (Finding something unexpected) ---
    "The character finds a small, colorful stone on the path.",
    "The character discovers a hidden door in their house.",
    "The character finds a lost toy in the park.",
    "The character discovers a small, handwritten note.",
    "The character finds a map that looks old.",
    "The character unearths something buried in the garden.",
    "The character finds a key that doesn't seem to belong to anything they know.",
    "The character discovers a beautiful flower they've never seen before.",
    "The character finds a small box with something inside.",
    "The character discovers footprints in the snow/sand.",
    "The character finds a single glove/sock lying on the ground.",
    "The character discovers a small, abandoned bird's nest.",
    "The character finds a coin that looks very old and shiny.",
    "The character discovers a drawing hidden inside a book.",
    "The character finds a set of colorful marbles scattered on the floor.",
    "The character discovers a small, locked diary.",
    "The character finds a feather that is an unusual color.",
    "The character discovers a strange symbol carved into a tree.",
    "The character finds a photograph that they don't recognize.",
    "The character discovers a set of small, animal figurines arranged neatly.",

    # --- Encounter Start (Meeting someone or something new) ---
    "The character meets a friendly dog in the park.",
    "The character encounters a new student at school.",
    "The character meets an elderly person who needs help.",
    "The character encounters a street performer.",
    "The character sees someone struggling to carry something.",
    "The character meets a lost child.",
    "The character encounters a talking animal (in a fantasy context, subtly implied).",
    "The character sees a group of people gathered around something.",
    "The character meets a new neighbor.",
    "The character encounters someone selling interesting food.",
    "The character sees someone waving to them from across the street, but they don't recognize them.",
    "The character encounters a cat that seems to be trying to lead them somewhere.",
    "The character meets a delivery person with a package for them, but they weren't expecting anything.",
    "The character sees someone wearing a very unusual hat.",
    "The character encounters a group of children playing a game they don't know.",
    "The character meets someone who is looking for directions.",
    "The character sees someone painting a picture in the park.",
    "The character encounters a musician playing a beautiful instrument.",
    "The character meets someone who seems to have dropped something important.",
    "The character sees someone looking lost and confused.",

    # --- Action Start (Character is already doing something) ---
    "The character is walking home from school/work.",
    "The character is playing in the park.",
    "The character is eating lunch at school/work.",
    "The character is reading a book in their room.",
    "The character is helping with chores at home.",
    "The character is riding a bike in the park.",
    "The character is drawing/painting a picture.",
    "The character is watering plants in the garden.",
    "The character is cooking a simple meal.",
    "The character is waiting for someone at a meeting place.",
    "The character is getting ready to go out.",
    "The character is cleaning their room.",
    "The character is practicing a musical instrument.",
    "The character is writing in a notebook.",
    "The character is looking out the window.",
    "The character is choosing what to wear for the day.",
    "The character is packing a bag.",
    "The character is setting the table for a meal.",
    "The character is organizing their desk/workspace.",
    "The character is looking at photos in an album.",

    # --- Question/Unusual Circumstance Start (Prompting curiosity) ---
    "The character notices that something is missing from their usual place.",
    "The character receives a mysterious message.",
    "The character realizes they have forgotten something important.",
    "The character sees something unusual happening outside their window.",
    "The character finds that their favorite thing is not working.",
    "The character wakes up and the weather is very different from yesterday.",
    "The character notices that time seems to be going by very quickly/slowly.",
    "The character finds that something in their house has moved to a different place.",
    "The character realizes they are in a place they don't recognize (subtly, within a familiar setting).",
    "The character hears a rumor about something interesting happening nearby.",
    "The character finds a door unlocked that they usually keep locked.",
    "The character sees a light turned on in a room that should be empty.",
    "The character realizes they have an extra item in their bag that they didn't put there.",
    "The character finds that their pet is behaving strangely.",
    "The character notices that a familiar sound is suddenly absent.",
    "The character receives a phone call from an unknown number.",
    "The character finds that their reflection in a mirror seems slightly different.",
    "The character realizes they are wearing mismatched socks/shoes.",
    "The character finds that their favorite snack is unexpectedly gone.",
    "The character notices that a clock in their house is showing the wrong time.",
]


all_japanese_names = [
    "Aiba", "Aika", "Aki", "Akihito", "Akihiro", "Akira", "Akari", "Akatsuki", "Akane", "Amato",
    "Amane", "Ami", "An", "Ao", "Aoi", "Arashi", "Arata", "Asahi", "Asuka", "Atsuki", "Ayumu",
    "Beniko", "Botan", "Chiaki", "Chiharu", "Chikao", "Chinatsu", "Chihiro", "Chou", "Daigo",
    "Daichi", "Daijiro", "Daiki", "Den", "Eiji", "Eito", "Ena", "Erika", "Fuji", "Fuuta", "Gaku",
    "Gin", "Ginga", "Goro", "Haku", "Hajime", "Haru", "Haruna", "Hayao", "Hayate",
    "Hazuki", "Hibiki", "Hideki", "Hideo", "Hikaru", "Hina", "Hinata", "Hiroki", "Hiroshi", "Hiroto",
    "Hiyo", "Homare", "Honami", "Honoka", "Hoshi", "Hotaka", "Hotaru", "Ibuki", "Ikkaku", "Inori",
    "Issei", "Itsuki", "Izumi", "Jin", "Jiro", "Jo", "Jouji", "Jun", "Junna", "Junpei", "Kaede",
    "Kaguya", "Kai", "Kaito", "Kakeru", "Kana", "Kanae", "Kanako", "Kanon", "Kanata", "Kanna",
    "Kaori", "Karin", "Kasumi", "Katsumi", "Kaoru", "Kazane", "Kazuhiko", "Kazuki", "Kazuma", "Kazumi",
    "Keigo", "Keiko", "Keisuke", "Keita", "Keito", "Ken", "Kenichi", "Kenji", "Kenshin", "Kenta",
    "Kira", "Kiyoka", "Kiyomasa", "Kiyomi", "Kiyora", "Kiyoshi", "Kokoa", "Koharu", "Koki", "Komugi",
    "Konatsu", "Kota", "Kotone", "Kotomi", "Kou", "Kouhei", "Kouki", "Kouta", "Kouya", "Luna",
    "Madoka", "Maho", "Mai", "Makoto", "Mamoru", "Manabu", "Manami", "Mao", "Marina", "Marin",
    "Masaki", "Masaru", "Masato", "Masayoshi", "Mayu", "Mei", "Michio", "Miharu", "Miki", "Miku",
    "Mina", "Minami", "Minato", "Minori", "Mio", "Miori", "Mitsu", "Mitsuki", "Miyu", "Mizuki",
    "Mizuho", "Moe", "Momiji", "Momoka", "Mutsuki", "Nagi", "Nagisa", "Nao", "Naohiro", "Naoki",
    "Naoto", "Nanami", "Natsuki", "Natsume", "Nene", "Niko", "Noboru", "Nobukazu", "Nonoka", "Nozomi",
    "Oka", "Osamu", "Rai", "Raiden", "Raiga", "Raito", "Raizo", "Raku", "Ramu", "Ran", "Ranji",
    "Rei", "Reiji", "Reina", "Remi", "Ren", "Renka", "Renji", "Riku", "Rikuo", "Rin", "Rina",
    "Rinon", "Rintaro", "Riona", "Ririka", "Risa", "Ritsu", "Rumi", "Runo", "Ruri", "Ruriha",
    "Ryoga", "Ryohei", "Ryouma", "Ryota", "Ryosei", "Ryusei", "Saburo", "Sachiko", "Saku", "Sakura",
    "Sakuyo", "Sanosuke", "Sango", "Sara", "Saki", "Sakuyo", "Sanosuke", "Sango", "Sara", "Saki",
    "Satoshi", "Satsuki", "Sayaka", "Seiji", "Sen", "Senichi", "Serina", "Setsuka", "Setsuna", "Shin",
    "Shinji", "Shion", "Shiori", "Shizuka", "Shogo", "Sho", "Shota", "Shun", "Shunya", "Sohma",
    "Sora", "Sota", "Sou", "Souma", "Subaru", "Suisei", "Sumire", "Sumireko", "Susumu", "Suzuka",
    "Taichi", "Taiga", "Taiyo", "Takashi", "Takumi", "Taku", "Takeshi", "Takeru", "Taro", "Tatsuya",
    "Tetsuya", "Toki", "Toma", "Tomoe", "Tomoki", "Tomomi", "Tomoya", "Toru", "Tsubaki", "Tsubasa",
    "Tsukasa", "Tsukiyo", "Tsumugi", "Tsuyu", "Tsuyoshi", "Ukyo", "Umi", "Utae", "Wakaba", "Wakana",
    "Wataru", "Yamato", "Yasuhiro", "Yae", "Yo", "Yoichi", "Yoko", "Yori", "Yosei", "Yoshiaki",
    "Yoshihiro", "Yoshiko", "Yoshio", "Youko", "Yuichi", "Yuito", "Yuuka", "Yuuki", "Yuukihiro", "Yukihito",
    "Yukiho", "Yukio", "Yuna", "Yuumi", "Yuu", "Yuuka", "Yuumi", "Yuusei", "Yuzuki", "Yuzuha", "Yuzuyu",
    "Yurara", "Yurika", "Yuto", "Yuuya", "Zen", "Zenjiro", "Zin", "Zoe"
]